### ISSUE TITLE
Climacell API Keys Still Working?

### ISSUE THREAD

**Issue by Dresch360** [mykle1/MMM-BMW-CC#5]
Thanks for building a great module. Attempted for the last two weeks to get MMM-BMW-CC to work with new Climacell API keys, however nothing seems to work. Also, Climacell no longer sends a confirmation email to verify the account. 

Here is the error message:
2021-01-04 22:09:22.021] [LOG]    Whoops! There was an uncaught exception...
[2021-01-04 22:09:22.021] [ERROR]  TypeError: result.slice is not a function
    at Request._callback (/home/pi/MagicMirror/modules/MMM-BMW-CC/node_helper.js:44:33)
    at Request.self.callback (/home/pi/MagicMirror/modules/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (/home/pi/MagicMirror/modules/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (/home/pi/MagicMirror/modules/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)

**Comment by mykle1** [comment]
The module is working as expected so I'm closing the issue.

If you need further assistance then post a topic on the MagicMirror forum

**Comment by Dresch360** [comment]
Hmm...API keys are still not working.

**Comment by mykle1** [comment]
So, I just downloaded a fresh install of BMW-CC and it fires right up with no errors. As I stated in my last response, "If you need further assistance then post a topic on the MagicMirror forum". Not sure why you posted here again. :-/

**Comment by mykle1** [comment]
Ok, so, the updated module now works with the new api keys. Sorry about the delay. I was using an older v3 api key. It still works but will be closed soon. The new api keys work with the new version 4 of the api itself. This module has been updated to make use of the new v4 api.

My apologies
